feat: 🎸 추가 사업자페이지에 매장 식별자 삽입
nhnacademy-be3-CookShoong/cookshoong-frontend pull request #85
Opened 2023-07-23 13:29 UTC by 10kseok

사업자 페이지에서 매장 식별자를 가져올 수 있게 path에서 매장식별자를 가져와서 링크들에 삽입해두었습니다.

2023-07-23 13:41 UTC, seong1542 approved these changes

2023-07-23 13:42 UTC, eora21 requested changes

2023-07-23 13:42 UTC, eora21 commented on src/main/resources/templates/fragments.html
> +      console.log("first", window.document.location.pathname.split("/")[0]);
log 제거해주세요

2023-07-23 13:42 UTC, eora21 commented on src/main/resources/templates/fragments.html
> +        console.log("href", navLink.getAttribute("href"));
log 제거해주세요

2023-07-24 01:09 UTC, eora21 approved these changes

2023-07-24 01:10 UTC, merged